In [1]:
import numpy as np

1. Crear un vector de ceros de tamaño 10

In [2]:
zeros = np.zeros(10)
print(zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Crea un vector de unos de tamaño 8.

In [3]:
x = np.ones(8)
print(x)

[1. 1. 1. 1. 1. 1. 1. 1.]


Crea un vector con los números del 10 al 20 (inclusive).

In [6]:
s = np.arange(10,21)
print(s)

[10 11 12 13 14 15 16 17 18 19 20]


Crea un array con 7 números equiespaciados entre 0 y 1.

In [9]:
d = np.linspace(0,1,7)
print(d)

[0.         0.16666667 0.33333333 0.5        0.66666667 0.83333333
 1.        ]


Crea una matriz 3×3 llena de 5.

In [ ]:
m = np.full((3,3),5)
print(m)

TypeError: Cannot interpret '5' as a data type