In [1]:
import numpy as np

#Crear un Array
arr = np.array([1, 2, 3, 4, 5])
print(arr)


[1 2 3 4 5]


In [2]:

#Crear un Array con ceros y unos 
zeros = np.zeros(10) #el parametro son el numero de ceros que tendra
print(zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Para generar una matriz se usa ((filas,columnas))

In [3]:
#Crear Matrices
ones = np.ones((2, 3))  #ones es para generar solo el numero uno
zeros = np.zeros((3,3)) #matriz de 3x3
print(f"\n matriz de unos:{ones}")
print(f"\n matriz de ceros:{zeros}")



 matriz de unos:[[1. 1. 1.]
 [1. 1. 1.]]

 matriz de ceros:[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [4]:
import numpy as np  #generar un array con una tupla

arr = np.array((1, 2, 3, 4, 5))

print(arr)

[1 2 3 4 5]


Numpy Full np.full()

In [5]:
#numpy full  #np.full(shape, fill_value, dtype=None)
full = np.full(5,7) #Array unidimensional (numero de elementos , valor de los elementos)
print(full)

[7 7 7 7 7]


In [6]:
full = np.full((5,3),8) #Crear una matriz ( (5 filas , 3 columnas ) valor de los elementos  )
print(full)

[[8 8 8]
 [8 8 8]
 [8 8 8]
 [8 8 8]
 [8 8 8]]


In [7]:
y = np.full((5,3),9,dtype=str) #asignar un tipo de dato a los objetos 
print(y)

x = np.full((10,10),10,dtype=float)
print(x)

[['9' '9' '9']
 ['9' '9' '9']
 ['9' '9' '9']
 ['9' '9' '9']
 ['9' '9' '9']]
[[10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]]


np.eye() - Sirve para crear matrices de identidad
Una matriz identidad es una matriz cuadrada con unos en la diagonal principal (de la esquina superior izquierda a la inferior derecha) y ceros en todas las demás posiciones
Características principales     Matriz cuadrada: Debe tener el mismo número de filas y columnas.  Diagonal principal: Todos los elementos en la diagonal principal son igual a \(1\).  Resto de elementos: Todos los elementos que no están en la diagonal principal son igual a \(0\). 


In [8]:
#matriz cuadrada
e = np.eye(3)
print(e)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [9]:
#matrix no cuadrada 
a = np.eye(5,2)
print(a)

[[1. 0.]
 [0. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


np.arange()
permite generar secuencias fácilmente.

np.arange(start, stop, step)


In [10]:
n = np.arange(1,11) #(valor inicial, final)
print(n)

[ 1  2  3  4  5  6  7  8  9 10]


In [11]:
a = np.arange(1,11,2) #(valor inicial,valor final, pasos)
print(a)

[1 3 5 7 9]


In [12]:

n = np.arange(0, 11, 2)
print(n)

[ 0  2  4  6  8 10]


np.linspace()

np.linspace(start, stop, num=50)


Parámetros principales:

start: valor inicial (incluido).

stop: valor final (incluido también, a diferencia de arange()).

num: cantidad de valores que quieres generar (por defecto son 50).

In [13]:
#np.linspace(inicio, fin, cantidad)
g = np.linspace(0, 10, 5)
print(g)

s=np.linspace(0,20,6)
print(s)

[ 0.   2.5  5.   7.5 10. ]
[ 0.  4.  8. 12. 16. 20.]


# Crear Arrays Aleatorios
🎲 np.random.rand()

Crea un array con valores flotantes aleatorios entre 0 y 1.

h = np.random.rand(2, 3)

In [14]:
r = np.random.rand(5,4)
print(r)

[[0.4334408  0.50560753 0.29441256 0.93700878]
 [0.65466974 0.3173449  0.07955248 0.25706833]
 [0.04307328 0.22930254 0.84921547 0.45740507]
 [0.64243655 0.92154222 0.97182921 0.68324873]
 [0.62933837 0.83052415 0.12553584 0.20361775]]


🎯 np.random.randint()

Crea enteros aleatorios dentro de un rango.

🧩 Sintaxis
np.random.randint(low, high, size)

Parámetro	Significado
low	valor mínimo (incluido)
high	valor máximo (no incluido)
size	forma o cantidad de números que quieres generar

In [15]:
i = np.random.randint(1,100,5)
print(f"nums aleatorios del 1 al 100, 5 veces : {i}")

n = np.random.randint(10,20,10)
print(f"nums aleatorios del 10 al 20, 10 veces : {n}")

nums aleatorios del 1 al 100, 5 veces : [85 60 36  5 33]
nums aleatorios del 10 al 20, 10 veces : [16 13 12 12 16 17 16 13 17 18]


generar matrices con numeros aleatorios

np.random.randit(desde, hasta, (filas,columnas))

In [16]:
x = np.random.randint(1, 10, (3, 3))    
print(x)


[[5 8 3]
 [1 9 9]
 [5 7 5]]


#⚙️ 6. Convertir el tipo de datos (dtype)
Puedes cambiar el tipo de un array.

print(a.astype(dtype))

In [17]:
a = np.array((2,3))
print(a.astype(int))
print(a.astype(str))
print(a.astype(float))


[2 3]
['2' '3']
[2. 3.]


#reshape()
np.reshape() sirve para cambiar la forma (shape) de un array sin modificar sus datos.

Es decir, reorganiza los mismos valores en una nueva estructura (más filas, más columnas, etc.), pero sin alterar el contenido.

🧩 Sintaxis
np.reshape(array, new_shape)

In [18]:
k = np.arange(12)
print(k)
print(k.reshape(3, 4))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [19]:
s = np.array([1,2,3,4,5,6,7,8,9,10])
print((s.reshape(2,5))) #(numero de filas, numero de columnas)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


# Parte 2 : Propiedades de los Arrays

Aprenderás a inspeccionar y entender un array:
su forma, dimensiones, tamaño, tipo de datos y más.

Estas propiedades te ayudarán a:

Saber si tu matriz tiene la forma correcta antes de operar.

Ver cuántos elementos hay.

Confirmar el tipo de datos con el que estás trabajando.

In [ ]:
# 1.   shape() --ver la forma de un array

arr = np.array([[1,2,3],
                [4,5,6]])
print(arr.shape)


#el resultad sera (2,3) significa 2 filas y 3 columnas


# 2.  tambien se puede cambiar esto con .reshape()

arr = arr.reshape(3,2)
print(arr.shape) 


#3. ndim --- numero de dimensiones Muestra cuántas dimensiones tiene el array (vector, matriz, tensor, etc).
print(f"numero de dimensiones : {arr.ndim}")


#size() --- devuelve el numero total de elementos 
print(f"numero total de elementos {arr.size}")


#dtype() tipo de datos de los elementos 
print(f"tipo de datos que contiene : {arr.dtype}")
#se puede crear un array con un tipo de dato especifico
arr2 = np.arange(1,10,dtype=float)
print(f"tipo de data de arr2 : {arr2.dtype}")


#itemsize — tamaño en bytes de cada elemento 
print(f"tamaño de bytes de cada elemento : {arr.itemsize} ")

#nbytes — tamaño total en memoria
print(f"tamaño total dela rray en la memoria : {arr.nbytes}")


#T — transpuesta (para matrices 2D) ---- Invierte filas por columnas.
print(arr.T)

#reshape --- Reorganiza los datos, sin cambiarlos.
arr3 = np.arange(12)
print(arr3.reshape(3,4)) #el resultado es el array ordenado de 0 a 11 con 3 filas de 4 elementos




(2, 3)
(3, 2)
numero de dimensiones : 2
numero total de elementos 6
tipo de datos que contiene : int64
tipo de data de arr2 : float64
tamaño de bytes de cada elemento : 8 
tamaño total dela rray en la memoria : 48
[[1 3 5]
 [2 4 6]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
