In [17]:
import numpy as np

#Crear un Array
arr = np.array([1, 2, 3, 4, 5])
print(arr)


[1 2 3 4 5]


In [18]:

#Crear un Array con ceros y unos 
zeros = np.zeros(10) #el parametro son el numero de ceros que tendra
print(zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Para generar una matriz se usa ((filas,columnas))

In [19]:
#Crear Matrices
ones = np.ones((2, 3))  #ones es para generar solo el numero uno
zeros = np.zeros((3,3)) #matriz de 3x3
print(f"\n matriz de unos:{ones}")
print(f"\n matriz de ceros:{zeros}")



 matriz de unos:[[1. 1. 1.]
 [1. 1. 1.]]

 matriz de ceros:[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [20]:
import numpy as np  #generar un array con una tupla

arr = np.array((1, 2, 3, 4, 5))

print(arr)

[1 2 3 4 5]


Numpy Full np.full()

In [21]:
#numpy full  #np.full(shape, fill_value, dtype=None)
full = np.full(5,7) #Array unidimensional (numero de elementos , valor de los elementos)
print(full)

[7 7 7 7 7]


In [22]:
full = np.full((5,3),8) #Crear una matriz ( (5 filas , 3 columnas ) valor de los elementos  )
print(full)

[[8 8 8]
 [8 8 8]
 [8 8 8]
 [8 8 8]
 [8 8 8]]


In [23]:
y = np.full((5,3),9,dtype=str) #asignar un tipo de dato a los objetos 
print(y)

x = np.full((10,10),10,dtype=float)
print(x)

[['9' '9' '9']
 ['9' '9' '9']
 ['9' '9' '9']
 ['9' '9' '9']
 ['9' '9' '9']]
[[10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]]


np.eye() - Sirve para crear matrices de identidad
Una matriz identidad es una matriz cuadrada con unos en la diagonal principal (de la esquina superior izquierda a la inferior derecha) y ceros en todas las demás posiciones
Características principales     Matriz cuadrada: Debe tener el mismo número de filas y columnas.  Diagonal principal: Todos los elementos en la diagonal principal son igual a \(1\).  Resto de elementos: Todos los elementos que no están en la diagonal principal son igual a \(0\). 


In [24]:
#matriz cuadrada
e = np.eye(3)
print(e)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [25]:
#matrix no cuadrada 
a = np.eye(5,2)
print(a)

[[1. 0.]
 [0. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


np.arange()
permite generar secuencias fácilmente.

np.arange(start, stop, step)


In [ ]:
n = np.arange(1,11) #(valor inicial, final)
print(n)

[ 1  2  3  4  5  6  7  8  9 10]


In [32]:
a = np.arange(1,11,2) #(valor inicial,valor final, pasos)
print(a)

[1 3 5 7 9]


In [30]:

n = np.arange(0, 11, 2)
print(n)

[ 0  2  4  6  8 10]
