In [16]:
import numpy as np

#Crear un Array
arr = np.array([1, 2, 3, 4, 5])
print(arr)


[1 2 3 4 5]


In [17]:

#Crear un Array con ceros y unos 
zeros = np.zeros(10) #el parametro son el numero de ceros que tendra
print(zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Para generar una matriz se usa ((filas,columnas))

In [18]:
#Crear Matrices
ones = np.ones((2, 3))  #ones es para generar solo el numero uno
zeros = np.zeros((3,3)) #matriz de 3x3
print(f"\n matriz de unos:{ones}")
print(f"\n matriz de ceros:{zeros}")



 matriz de unos:[[1. 1. 1.]
 [1. 1. 1.]]

 matriz de ceros:[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [19]:
import numpy as np  #generar un array con una tupla

arr = np.array((1, 2, 3, 4, 5))

print(arr)

[1 2 3 4 5]


Numpy Full np.full()

In [20]:
#numpy full  #np.full(shape, fill_value, dtype=None)
full = np.full(5,7) #Array unidimensional (numero de elementos , valor de los elementos)
print(full)

[7 7 7 7 7]


In [21]:
full = np.full((5,3),8) #Crear una matriz ( (5 filas , 3 columnas ) valor de los elementos  )
print(full)

[[8 8 8]
 [8 8 8]
 [8 8 8]
 [8 8 8]
 [8 8 8]]


In [22]:
y = np.full((5,3),9,dtype=str) #asignar un tipo de dato a los objetos 
print(y)

x = np.full((10,10),10,dtype=float)
print(x)

[['9' '9' '9']
 ['9' '9' '9']
 ['9' '9' '9']
 ['9' '9' '9']
 ['9' '9' '9']]
[[10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]]


np.eye() - Sirve para crear matrices de identidad
Una matriz identidad es una matriz cuadrada con unos en la diagonal principal (de la esquina superior izquierda a la inferior derecha) y ceros en todas las demás posiciones
Características principales     Matriz cuadrada: Debe tener el mismo número de filas y columnas.  Diagonal principal: Todos los elementos en la diagonal principal son igual a \(1\).  Resto de elementos: Todos los elementos que no están en la diagonal principal son igual a \(0\). 


In [23]:
#matriz cuadrada
e = np.eye(3)
print(e)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [24]:
#matrix no cuadrada 
a = np.eye(5,2)
print(a)

[[1. 0.]
 [0. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


np.arange()
permite generar secuencias fácilmente.

np.arange(start, stop, step)


In [25]:
n = np.arange(1,11) #(valor inicial, final)
print(n)

[ 1  2  3  4  5  6  7  8  9 10]


In [26]:
a = np.arange(1,11,2) #(valor inicial,valor final, pasos)
print(a)

[1 3 5 7 9]


In [27]:

n = np.arange(0, 11, 2)
print(n)

[ 0  2  4  6  8 10]


np.linspace()

np.linspace(start, stop, num=50)


Parámetros principales:

start: valor inicial (incluido).

stop: valor final (incluido también, a diferencia de arange()).

num: cantidad de valores que quieres generar (por defecto son 50).

In [28]:
g = np.linspace(0, 10, 5)
print(g)

s=np.linspace(0,20,6)
print(s)

[ 0.   2.5  5.   7.5 10. ]
[ 0.  4.  8. 12. 16. 20.]


# Crear Arrays Aleatorios
🎲 np.random.rand()

Crea un array con valores flotantes aleatorios entre 0 y 1.

h = np.random.rand(2, 3)

In [29]:
r = np.random.rand(5,4)
print(r)

[[0.60784311 0.56297329 0.19941226 0.27329062]
 [0.10719128 0.19650405 0.80954466 0.90966002]
 [0.50361675 0.5305342  0.13581378 0.93113002]
 [0.10220027 0.54192879 0.84094296 0.970502  ]
 [0.53956562 0.94251814 0.17671425 0.54179388]]


🎯 np.random.randint()

Crea enteros aleatorios dentro de un rango.

🧩 Sintaxis
np.random.randint(low, high, size)

Parámetro	Significado
low	valor mínimo (incluido)
high	valor máximo (no incluido)
size	forma o cantidad de números que quieres generar

In [35]:
i = np.random.randint(1,100,5)
print(f"nums aleatorios del 1 al 100, 5 veces : {i}")

n = np.random.randint(10,20,10)
print(f"nums aleatorios del 10 al 20, 10 veces : {n}")

nums aleatorios del 1 al 100, 5 veces : [11 17 57 52 21]
nums aleatorios del 10 al 20, 10 veces : [10 12 19 10 14 19 15 17 13 11]


generar matrices con numeros aleatorios

np.random.randit(desde, hasta, (filas,columnas))

In [ ]:
x = np.random.randint(1, 10, (3, 3))    
print(x)


[[4 3 2]
 [1 3 9]
 [3 1 3]]
