In [1]:
import numpy as np

1. Crear un vector de ceros de tamaño 10

In [2]:
zeros = np.zeros(10)
print(zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Crea un vector de unos de tamaño 8.

In [3]:
x = np.ones(8)
print(x)

[1. 1. 1. 1. 1. 1. 1. 1.]


Crea un vector con los números del 10 al 20 (inclusive).

In [4]:
s = np.arange(10,21)
print(s)

[10 11 12 13 14 15 16 17 18 19 20]


Crea un array con 7 números equiespaciados entre 0 y 1.

In [5]:
d = np.linspace(0,1,7)
print(d)

[0.         0.16666667 0.33333333 0.5        0.66666667 0.83333333
 1.        ]


Crea una matriz 3×3 llena de 5.

In [6]:
m = np.full((3,3),5)
print(m)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


Crea una matriz identidad de 5×5.

In [7]:
q = np.eye(5,5)
print(q)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Crea una matriz 4×3 con números enteros aleatorios entre 0 y 50.

In [8]:
ax = np.random.randint(0,50,(4,3))
print(ax)

[[45 17  6]
 [ 2 23 28]
 [ 9 18 23]
 [32  7 40]]


Crea una matriz 2×6 con números aleatorios entre 0 y 1.

In [9]:
xx = np.random.randint(0,1,(2,6))
print(xx)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]]


Crea un array de 15 elementos del 1 al 15 y reorganízalo en una matriz 3×5.

In [10]:
arr1 = np.arange(1,16)
print(arr1)
arr_reshaped = arr1.reshape(3,5)
print(arr_reshaped)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


Crea un array con los múltiplos de 3 desde 0 hasta 30.

In [11]:
arr = np.arange(0,31,3)
print(arr)

[ 0  3  6  9 12 15 18 21 24 27 30]


🧠 Mini Reto

1️⃣ Crea un array con los números del 1 al 12.
2️⃣ Reorganízalo en una matriz 3×4.
3️⃣ Imprime:

Su forma (shape)

Su número de dimensiones (ndim)

Su tipo de datos (dtype)

Su tamaño total (size)

Su transpuesta (T)

In [18]:
a = np.arange(1,13)
print(a.reshape(3,4))
print(a.shape)
print(a.dtype)
print(a.ndim)
print(a.size)
print(a.T)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(12,)
int64
1
12
[ 1  2  3  4  5  6  7  8  9 10 11 12]
