In [40]:
import numpy as np

#Crear un Array
arr = np.array([1, 2, 3, 4, 5])
print(arr)


[1 2 3 4 5]


In [41]:

#Crear un Array con ceros y unos 
zeros = np.zeros(10) #el parametro son el numero de ceros que tendra
print(zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Para generar una matriz se usa ((filas,columnas))

In [42]:
#Crear Matrices
ones = np.ones((2, 3))  #ones es para generar solo el numero uno
zeros = np.zeros((3,3)) #matriz de 3x3
print(f"\n matriz de unos:{ones}")
print(f"\n matriz de ceros:{zeros}")



 matriz de unos:[[1. 1. 1.]
 [1. 1. 1.]]

 matriz de ceros:[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [43]:
import numpy as np  #generar un array con una tupla

arr = np.array((1, 2, 3, 4, 5))

print(arr)

[1 2 3 4 5]


Numpy Full np.full()

In [44]:
#numpy full  #np.full(shape, fill_value, dtype=None)
full = np.full(5,7) #Array unidimensional (numero de elementos , valor de los elementos)
print(full)

[7 7 7 7 7]


In [45]:
full = np.full((5,3),8) #Crear una matriz ( (5 filas , 3 columnas ) valor de los elementos  )
print(full)

[[8 8 8]
 [8 8 8]
 [8 8 8]
 [8 8 8]
 [8 8 8]]


In [46]:
y = np.full((5,3),9,dtype=str) #asignar un tipo de dato a los objetos 
print(y)

x = np.full((10,10),10,dtype=float)
print(x)

[['9' '9' '9']
 ['9' '9' '9']
 ['9' '9' '9']
 ['9' '9' '9']
 ['9' '9' '9']]
[[10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]]


np.eye() - Sirve para crear matrices de identidad
Una matriz identidad es una matriz cuadrada con unos en la diagonal principal (de la esquina superior izquierda a la inferior derecha) y ceros en todas las demás posiciones
Características principales     Matriz cuadrada: Debe tener el mismo número de filas y columnas.  Diagonal principal: Todos los elementos en la diagonal principal son igual a \(1\).  Resto de elementos: Todos los elementos que no están en la diagonal principal son igual a \(0\). 


In [47]:
#matriz cuadrada
e = np.eye(3)
print(e)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [48]:
#matrix no cuadrada 
a = np.eye(5,2)
print(a)

[[1. 0.]
 [0. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


np.arange()
permite generar secuencias fácilmente.

np.arange(start, stop, step)


In [49]:
n = np.arange(1,11) #(valor inicial, final)
print(n)

[ 1  2  3  4  5  6  7  8  9 10]


In [50]:
a = np.arange(1,11,2) #(valor inicial,valor final, pasos)
print(a)

[1 3 5 7 9]


In [51]:

n = np.arange(0, 11, 2)
print(n)

[ 0  2  4  6  8 10]


np.linspace()

np.linspace(start, stop, num=50)


Parámetros principales:

start: valor inicial (incluido).

stop: valor final (incluido también, a diferencia de arange()).

num: cantidad de valores que quieres generar (por defecto son 50).

In [ ]:
#np.linspace(inicio, fin, cantidad)
g = np.linspace(0, 10, 5)
print(g)

s=np.linspace(0,20,6)
print(s)

[ 0.   2.5  5.   7.5 10. ]
[ 0.  4.  8. 12. 16. 20.]


# Crear Arrays Aleatorios
🎲 np.random.rand()

Crea un array con valores flotantes aleatorios entre 0 y 1.

h = np.random.rand(2, 3)

In [63]:
r = np.random.rand(5,4)
print(r)

[[0.7580523  0.96655899 0.25360607 0.75050099]
 [0.8887975  0.59433801 0.6729223  0.01282432]
 [0.76277947 0.86905383 0.47891361 0.17869641]
 [0.04463321 0.27098146 0.93993801 0.56711008]
 [0.05679224 0.80070695 0.54576496 0.1762985 ]]


🎯 np.random.randint()

Crea enteros aleatorios dentro de un rango.

🧩 Sintaxis
np.random.randint(low, high, size)

Parámetro	Significado
low	valor mínimo (incluido)
high	valor máximo (no incluido)
size	forma o cantidad de números que quieres generar

In [64]:
i = np.random.randint(1,100,5)
print(f"nums aleatorios del 1 al 100, 5 veces : {i}")

n = np.random.randint(10,20,10)
print(f"nums aleatorios del 10 al 20, 10 veces : {n}")

nums aleatorios del 1 al 100, 5 veces : [96 15 40 77 22]
nums aleatorios del 10 al 20, 10 veces : [19 17 11 12 15 13 14 18 15 17]


generar matrices con numeros aleatorios

np.random.randit(desde, hasta, (filas,columnas))

In [65]:
x = np.random.randint(1, 10, (3, 3))    
print(x)


[[1 6 4]
 [6 4 7]
 [7 7 9]]


#⚙️ 6. Convertir el tipo de datos (dtype)
Puedes cambiar el tipo de un array.

print(a.astype(dtype))

In [66]:
a = np.array((2,3))
print(a.astype(int))
print(a.astype(str))
print(a.astype(float))


[2 3]
['2' '3']
[2. 3.]


#reshape()
np.reshape() sirve para cambiar la forma (shape) de un array sin modificar sus datos.

Es decir, reorganiza los mismos valores en una nueva estructura (más filas, más columnas, etc.), pero sin alterar el contenido.

🧩 Sintaxis
np.reshape(array, new_shape)

In [67]:
k = np.arange(12)
print(k)
print(k.reshape(3, 4))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
s = np.array([1,2,3,4,5,6,7,8,9,10])
print((s.reshape(2,5))) #(numero de filas, numero de columnas)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
